# Generated by Django 6.0.2 on 2026-04-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='learning_objectives',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choices', to='core.quizquestion')),
            ],
        ),
    ]
